"""Pygame renderer for bubble sort visualization.

This module owns only window/event/render concerns and consumes SortStep data
generated by sorting_logic.bubble_sort_steps.
"""

from sorting_logic import bubble_sort_steps

try:
    import pygame
except ImportError:  # pragma: no cover - optional runtime dependency
    pygame = None


def visualize_bubble_sort_pygame(
    arr: list[int], width: int = 1100, height: int = 600, fps: int = 20
) -> None:
    """Visualize bubble sort using a Pygame window.

    Rendering flow:
    1. Build all sort steps from logic module.
    2. Run event loop until window close.
    3. Draw one frame per step (header + bars + footer).
    4. Advance step index at configured FPS.
    """
    if pygame is None:
        raise ImportError("Pygame is not installed. Run: pip install pygame-ce")

    pygame.init()
    pygame.display.set_caption("Bubble Sort Visualizer")
    screen = pygame.display.set_mode((width, height))
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("consolas", 24)
    small_font = pygame.font.SysFont("consolas", 18)

    original = arr.copy()
    steps = list(bubble_sort_steps(arr))
    step_index = 0
    running = True

    while running:
        # 1) Handle window events first.
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        if not running:
            break

        # 2) Pull current visualization state.
        step = steps[min(step_index, len(steps) - 1)]
        values = step.values
        compare_index = step.compare_index
        end_index = step.end_index

        # 3) Draw background and text metadata.
        screen.fill((8, 11, 20))

        header = (
            f"Pass: {step.pass_index} | Comparing index: {compare_index} | "
            f"Action: {step.action} | Swapped this step: {step.swapped_this_step}"
        )
        header_surface = font.render(header, True, (120, 240, 120))
        screen.blit(header_surface, (20, 18))

        end_surface = small_font.render(
            f"Unsorted end index: {end_index}", True, (170, 210, 170)
        )
        screen.blit(end_surface, (20, 52))

        # 4) Draw bars for current array state.
        if values:
            max_value = max(max(values), 1)
            left_pad = 20
            right_pad = 20
            bottom_pad = 70
            top_pad = 95
            usable_width = max(1, width - left_pad - right_pad)
            usable_height = max(1, height - top_pad - bottom_pad)
            bar_width = max(2, usable_width // len(values))

            for idx, value in enumerate(values):
                bar_h = int((max(value, 0) / max_value) * usable_height)
                x = left_pad + idx * bar_width
                y = height - bottom_pad - bar_h

                # Default, compare-highlight, and sorted-tail colors.
                color = (90, 180, 255)
                if compare_index is not None and idx in (compare_index, compare_index + 1):
                    color = (255, 180, 80)
                elif idx > end_index:
                    color = (120, 220, 120)

                pygame.draw.rect(screen, color, (x, y, bar_width - 2, bar_h))

                label = small_font.render(str(value), True, (220, 230, 240))
                screen.blit(label, (x, height - bottom_pad + 8))

        footer = small_font.render(f"Original: {original}", True, (200, 200, 200))
        screen.blit(footer, (20, height - 28))

        pygame.display.flip()

        # 5) Advance playback.
        if step_index < len(steps) - 1:
            step_index += 1

        clock.tick(max(1, fps))

    pygame.quit()
